from enum import Enum


class Jurisdiction(str, Enum):
    FEDERAL = "FEDERAL"
    STATE = "STATE"
    MUNICIPAL = "MUNICIPAL"
    DISTRICT_FEDERAL = "DISTRICT_FEDERAL"
    INTERNATIONAL = "INTERNATIONAL"
    OTHER = "OTHER"


class DocumentType(str, Enum):
    CONSTITUTION = "CONSTITUTION"
    CONSTITUTIONAL_AMENDMENT = "CONSTITUTIONAL_AMENDMENT"
    COMPLEMENTARY_LAW = "COMPLEMENTARY_LAW"
    ORDINARY_LAW = "ORDINARY_LAW"
    DECREE_LAW = "DECREE_LAW"
    DECREE = "DECREE"
    ORDINANCE = "ORDINANCE"
    INSTRUCTION = "INSTRUCTION"
    NORMATIVE_INSTRUCTION = "NORMATIVE_INSTRUCTION"
    RESOLUTION = "RESOLUTION"
    CONVINCING_AGREEMENT = "CONVINCING_AGREEMENT"
    SINIEF_ADJUSTMENT = "SINIEF_ADJUSTMENT"
    CONVENIO = "CONVENIO"
    ACT = "ACT"
    DECLARATORY_ACT = "DECLARATORY_ACT"
    CONSULTATION = "CONSULTATION"
    JUDICIAL_DECISION = "JUDICIAL_DECISION"
    OTHER = "OTHER"


class VersionStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    SUPERSEDED = "SUPERSEDED"
    UNKNOWN = "UNKNOWN"


class LegalNodeType(str, Enum):
    NORMA = "NORMA"
    LIVRO = "LIVRO"
    TITULO = "TITULO"
    CAPITULO = "CAPITULO"
    SECAO = "SECAO"
    SUBSECAO = "SUBSECAO"
    ARTIGO = "ARTIGO"
    PARAGRAFO = "PARAGRAFO"
    INCISO = "INCISO"
    ALINEA = "ALINEA"
    ITEM = "ITEM"
    NOTA = "NOTA"
    ANEXO = "ANEXO"
    OUTRO = "OUTRO"


class LegalRelationType(str, Enum):
    AMENDS = "AMENDS"
    REVOKES = "REVOKES"
    REGULATES = "REGULATES"
    REFERENCES = "REFERENCES"
    COMPLEMENTS = "COMPLEMENTS"
    SUPERSEDES = "SUPERSEDES"
    RATIFIES = "RATIFIES"
    VETOES = "VETOES"
    SUSPENDS = "SUSPENDS"


class TaxRegime(str, Enum):
    SIMPLES_NACIONAL = "SIMPLES_NACIONAL"
    LUCRO_PRESUMIDO = "LUCRO_PRESUMIDO"
    LUCRO_REAL = "LUCRO_REAL"
    MEI = "MEI"
    OTHER = "OTHER"


class TaxType(str, Enum):
    ICMS = "ICMS"
    ICMS_ST = "ICMS_ST"
    DIFAL = "DIFAL"
    PIS = "PIS"
    COFINS = "COFINS"
    ISS = "ISS"
    IPI = "IPI"
    CBS = "CBS"
    IBS = "IBS"
    IS = "IS"


class ClassificationStatus(str, Enum):
    CLASSIFIED = "CLASSIFIED"
    PARTIALLY_CLASSIFIED = "PARTIALLY_CLASSIFIED"
    UNCLASSIFIED = "UNCLASSIFIED"
    CONFIRMED = "CONFIRMED"
    PROVISIONAL = "PROVISIONAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    CONFLICTING = "CONFLICTING"
    INSUFFICIENT_LEGAL_BASIS = "INSUFFICIENT_LEGAL_BASIS"
    UNKNOWN = "UNKNOWN"


class DecisionStatus(str, Enum):
    APPROVED = "APPROVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    CONFLICT = "CONFLICT"
    FISCAL_RULE_CONFLICT = "FISCAL_RULE_CONFLICT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NO_APPLICABLE_RULE = "NO_APPLICABLE_RULE"
    FISCAL_RULE_NOT_FOUND = "FISCAL_RULE_NOT_FOUND"
    RULE_NOT_FOUND = "RULE_NOT_FOUND"
    LEGAL_BASIS_MISSING = "LEGAL_BASIS_MISSING"
    INSUFFICIENT_LEGAL_BASIS = "INSUFFICIENT_LEGAL_BASIS"


class FieldState(str, Enum):
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_PROVIDED = "NOT_PROVIDED"


class OperationType(str, Enum):
    INTERNAL = "INTERNAL"
    INTERSTATE = "INTERSTATE"
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"


class CustomerType(str, Enum):
    TAXPAYER = "TAXPAYER"
    NON_TAXPAYER = "NON_TAXPAYER"
    FINAL_CONSUMER = "FINAL_CONSUMER"


class InvoicePurpose(str, Enum):
    NORMAL = "NORMAL"
    COMPLEMENTARY = "COMPLEMENTARY"
    ADJUSTMENT = "ADJUSTMENT"
    RETURN = "RETURN"


class NodeStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    SUSPENDED = "SUSPENDED"
    DRAFT = "DRAFT"


class SourcePolicy(str, Enum):
    PRIMARY_OFFICIAL = "PRIMARY_OFFICIAL"
    SECONDARY_OFFICIAL = "SECONDARY_OFFICIAL"
    OFFICIAL_MIRROR = "OFFICIAL_MIRROR"
    REFERENCE = "REFERENCE"
    UNTRUSTED = "UNTRUSTED"


class ChangeStatus(str, Enum):
    NEW = "NEW"
    UNCHANGED = "UNCHANGED"
    CHANGED = "CHANGED"
    REMOVED = "REMOVED"
    UNAVAILABLE = "UNAVAILABLE"


class IdentityMatchStatus(str, Enum):
    EXACT_MATCH = "EXACT_MATCH"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    NO_MATCH = "NO_MATCH"


class TemporalStatus(str, Enum):
    EFFECTIVE = "EFFECTIVE"
    NOT_YET_EFFECTIVE = "NOT_YET_EFFECTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    TEMPORAL_GAP = "TEMPORAL_GAP"
    TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
    NOT_FOUND = "NOT_FOUND"


class RevocationType(str, Enum):
    TOTAL = "TOTAL"
    PARTIAL = "PARTIAL"


class LegalAnswerStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
    TEMPORAL_GAP = "TEMPORAL_GAP"
    PROVENANCE_FAILURE = "PROVENANCE_FAILURE"
    CONFLICTING_SOURCES = "CONFLICTING_SOURCES"
    ABSTAINED = "ABSTAINED"
